/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'dsilva' at '5/4/17 6:22 PM' with Gradle 2.12
 *
 * @author dsilva, @date 5/4/17 6:22 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
